### ISSUE TITLE
GSoC student proposal template

### ISSUE THREAD

**Issue by daminisatya** [salesforce/gsoc#5]
We must have a template for students to apply. Generally, every organization has a template with a set of questions to evaluate a student's proposal.

For example, 

https://github.com/cncf/soc/blob/master/PROJECT_IDEA_TEMPLATE.md
https://gdoc.pub/doc/e/2PACX-1vSo0ZDiTv4hTDktG7eo6Rp9vVXW5fEe6CF22fVi9AGcHVpWDE_kozxx_XI74tIU9g_Ge9cUHhSQgSUU

@amateurhuman

**Comment by sinAshish** [comment]
The codebase looks huge and the issues a bit tough, how do I get familiar with Transmogri.ai ?

**Comment by tanhengyeow** [comment]
@sinAshish Hi, I would suggest reading the [docs](https://docs.transmogrif.ai/en/stable/) to get familiar with the project. After that, I would say this [list](https://github.com/salesforce/TransmogrifAI/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) would be a good starting point to get familiar with the project's commit workflow and also allow one to dive a little into the codebase.

Anyway, I don't think this issue is suitable for asking questions not related to the issue title and I suggest filing a [new issue](https://github.com/salesforce/gsoc/issues/new) to ask other questions you might have :)

**Comment by sinAshish** [comment]
thought it would be silly to open a new issue for such a question!
